# -*- coding: utf-8 -*-
"""Innomatics_task_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fYvg2x3vX1cVYVlEXB6xD97N1lFNUUXc
"""

!pip uninstall -y transformers accelerate datasets tokenizers
!pip install transformers==4.37.2
!pip install accelerate==0.26.1
!pip install datasets==2.16.1
!pip install seqeval
!pip uninstall -y peft

import transformers, datasets, accelerate

print(transformers.__version__)
print(datasets.__version__)
print(accelerate.__version__)

import numpy as np
from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForTokenClassification,
    TrainingArguments,
    Trainer
)
from seqeval.metrics import f1_score

dataset = load_dataset("conll2003")
print(dataset)

label_list = dataset["train"].features["pos_tags"].feature.names
print(label_list)

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize_and_align_labels(example):
    tokenized_inputs = tokenizer(
        example["tokens"],
        truncation=True,
        padding="max_length",   # ✅ FIX
        max_length=128,         # ✅ FIX
        is_split_into_words=True
    )

    word_ids = tokenized_inputs.word_ids()
    previous_word_idx = None
    label_ids = []

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(example["pos_tags"][word_idx])
        else:
            label_ids.append(-100)

        previous_word_idx = word_idx

    tokenized_inputs["labels"] = label_ids
    return tokenized_inputs

tokenized_datasets = dataset.map(tokenize_and_align_labels)

model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label_list),
    id2label={i: l for i, l in enumerate(label_list)},
    label2id={l: i for i, l in enumerate(label_list)}
)

training_args = TrainingArguments(
    output_dir="./results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs"
)

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_labels = [
        [label_list[l] for l in label if l != -100]
        for label in labels
    ]

    true_predictions = [
        [label_list[p] for p, l in zip(pred, lab) if l != -100]
        for pred, lab in zip(predictions, labels)
    ]

    return {
        "f1": f1_score(true_labels, true_predictions)
    }

from transformers import DataCollatorForTokenClassification
data_collator = DataCollatorForTokenClassification(tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

results = trainer.evaluate()
print(results)

import torch

def predict(sentence):
    tokens = sentence.split()

    inputs = tokenizer(
        tokens,
        return_tensors="pt",
        is_split_into_words=True,
        truncation=True,
        padding=True
    )

    # ✅ FIX: move inputs to same device as model
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    inputs = {k: v.to(device) for k, v in inputs.items()}

    outputs = model(**inputs).logits
    predictions = outputs.argmax(dim=2)

    predicted_labels = [label_list[p.item()] for p in predictions[0]]

    print("\nPrediction:\n")
    for token, label in zip(tokens, predicted_labels[1:len(tokens)+1]):
        print(f"{token} -> {label}")

string=input("Enter a sentence: ")
predict(string)

chunk_label_list = dataset["train"].features["chunk_tags"].feature.names
print(chunk_label_list)

def tokenize_and_align_chunk_labels(example):
    tokenized_inputs = tokenizer(
        example["tokens"],
        truncation=True,
        padding="max_length",
        max_length=128,
        is_split_into_words=True
    )

    word_ids = tokenized_inputs.word_ids()
    previous_word_idx = None
    label_ids = []

    for word_idx in word_ids:
        if word_idx is None:
            label_ids.append(-100)
        elif word_idx != previous_word_idx:
            label_ids.append(example["chunk_tags"][word_idx])  # ✅ chunk labels
        else:
            label_ids.append(-100)

        previous_word_idx = word_idx

    tokenized_inputs["labels"] = label_ids
    return tokenized_inputs

chunk_tokenized = dataset.map(tokenize_and_align_chunk_labels)

chunk_model = AutoModelForTokenClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(chunk_label_list),
    id2label={i: l for i, l in enumerate(chunk_label_list)},
    label2id={l: i for i, l in enumerate(chunk_label_list)}
)

chunk_trainer = Trainer(
    model=chunk_model,
    args=training_args,
    train_dataset=chunk_tokenized["train"],
    eval_dataset=chunk_tokenized["validation"],
    tokenizer=tokenizer,
    data_collator=data_collator
)

chunk_trainer.train()

chunk_results = chunk_trainer.evaluate()
print(chunk_results)

import torch

def predict_both(sentence):
    tokens = sentence.split()

    inputs = tokenizer(
        tokens,
        return_tensors="pt",
        is_split_into_words=True,
        truncation=True,
        padding=True
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # POS
    model.to(device)
    pos_inputs = {k: v.to(device) for k, v in inputs.items()}
    pos_outputs = model(**pos_inputs).logits
    pos_preds = pos_outputs.argmax(dim=2)

    # Chunk
    chunk_model.to(device)
    chunk_inputs = {k: v.to(device) for k, v in inputs.items()}
    chunk_outputs = chunk_model(**chunk_inputs).logits
    chunk_preds = chunk_outputs.argmax(dim=2)

    print("\nFinal Prediction:\n")
    for i, token in enumerate(tokens):
        pos = label_list[pos_preds[0][i+1].item()]
        chunk = chunk_label_list[chunk_preds[0][i+1].item()]
        print(f"{token:12} POS: {pos:6} | Chunk: {chunk}")

predict_both("John works at Google in California")